# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\DB_project\ui\teacher_ui\info.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import  QWidget

class Ui_info(QWidget):
    def setupUi(self, info):
        info.setObjectName("info")
        info.resize(970, 589)
        self.label_title = QtWidgets.QLabel(info)
        self.label_title.setGeometry(QtCore.QRect(350, 30, 231, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(24)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.label_name = QtWidgets.QLabel(info)
        self.label_name.setGeometry(QtCore.QRect(120, 170, 221, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(24)
        self.label_name.setFont(font)
        self.label_name.setObjectName("label_name")
        self.label_sex = QtWidgets.QLabel(info)
        self.label_sex.setGeometry(QtCore.QRect(120, 230, 181, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(24)
        self.label_sex.setFont(font)
        self.label_sex.setObjectName("label_sex")
        self.label_age = QtWidgets.QLabel(info)
        self.label_age.setGeometry(QtCore.QRect(120, 290, 221, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(24)
        self.label_age.setFont(font)
        self.label_age.setObjectName("label_age")
        self.label_credit = QtWidgets.QLabel(info)
        self.label_credit.setGeometry(QtCore.QRect(120, 430, 251, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(24)
        self.label_credit.setFont(font)
        self.label_credit.setObjectName("label_credit")
        self.label_Area = QtWidgets.QLabel(info)
        self.label_Area.setGeometry(QtCore.QRect(120, 360, 461, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(24)
        self.label_Area.setFont(font)
        self.label_Area.setObjectName("label_Area")
        self.label_Sno = QtWidgets.QLabel(info)
        self.label_Sno.setGeometry(QtCore.QRect(120, 110, 421, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(24)
        self.label_Sno.setFont(font)
        self.label_Sno.setObjectName("label_Sno")

        self.retranslateUi(info)
        QtCore.QMetaObject.connectSlotsByName(info)

    def retranslateUi(self, info):
        _translate = QtCore.QCoreApplication.translate
        info.setWindowTitle(_translate("info", "Form"))
        self.label_title.setText(_translate("info", "个人信息"))
        self.label_name.setText(_translate("info", "姓名：苏步青"))
        self.label_sex.setText(_translate("info", "性别：男"))
        self.label_age.setText(_translate("info", "年龄：39"))
        self.label_credit.setText(_translate("info", "职称：讲师"))
        self.label_Area.setText(_translate("info", "电话号码：13545222586"))
        self.label_Sno.setText(_translate("info", "教师编号:"))
