from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import  QWidget

# class Ui_login_form(QWidget):
class Ui_login_form(object):
    def setupUi(self, login_form):
        login_form.setObjectName("login_form")
        login_form.resize(736, 687)
        login_form.setAutoFillBackground(False)
        self.login_button = PushButton(login_form)
        self.login_button.setGeometry(QtCore.QRect(300, 590, 121, 51))
        self.login_button.setObjectName("login_button")
        self.label = QtWidgets.QLabel(login_form)
        self.label.setGeometry(QtCore.QRect(180, 40, 381, 31))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(login_form)
        self.widget.setGeometry(QtCore.QRect(170, 440, 381, 121))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.password_input = LineEdit(self.widget)
        self.password_input.setObjectName("password_input")
        self.gridLayout.addWidget(self.password_input, 1, 1, 1, 1)
        self.username_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        self.username_label.setFont(font)
        self.username_label.setObjectName("username_label")
        self.gridLayout.addWidget(self.username_label, 0, 0, 1, 1)
        self.password_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        self.password_label.setFont(font)
        self.password_label.setObjectName("password_label")
        self.gridLayout.addWidget(self.password_label, 1, 0, 1, 1)
        self.username_input = LineEdit(self.widget)
        self.username_input.setObjectName("username_input")
        self.gridLayout.addWidget(self.username_input, 0, 1, 1, 1)
        self.splitter_2 = QtWidgets.QSplitter(login_form)
        self.splitter_2.setGeometry(QtCore.QRect(70, 80, 600, 331))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.head_img_label = PixmapLabel(self.splitter_2)
        self.head_img_label.setEnabled(True)
        self.head_img_label.setObjectName("head_img_label")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.user_type_combo = ComboBox(self.splitter)
        self.user_type_combo.setObjectName("user_type_combo")
        self.hint_label = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.hint_label.setFont(font)
        self.hint_label.setObjectName("hint_label")

        self.retranslateUi(login_form)
        QtCore.QMetaObject.connectSlotsByName(login_form)

    def retranslateUi(self, login_form):
        _translate = QtCore.QCoreApplication.translate
        login_form.setWindowTitle(_translate("login_form", "Form"))
        self.login_button.setText(_translate("login_form", "登录"))
        self.label.setText(_translate("login_form", "欢迎登录高校数据库管理系统！！！"))
        self.username_label.setText(_translate("login_form", "账        户 ："))
        self.password_label.setText(_translate("login_form", "密        码  ："))
        self.hint_label.setText(_translate("login_form", "请先使用下拉框选择用户类型"))
from qfluentwidgets import ComboBox, LineEdit, PixmapLabel, PushButton
