# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\DB_project\ui\students_info_Sno.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import  QWidget

class Ui_Students_info_Sno(QWidget):
    def setupUi(self, Students_info_Sno):
        Students_info_Sno.setObjectName("Students_info_Sno")
        Students_info_Sno.resize(664, 686)
        self.gridLayout = QtWidgets.QGridLayout(Students_info_Sno)
        self.gridLayout.setObjectName("gridLayout")
        self.dataTable_Vlayout = QtWidgets.QVBoxLayout()
        self.dataTable_Vlayout.setObjectName("dataTable_Vlayout")
        self.resultHint_label = QtWidgets.QLabel(Students_info_Sno)
        self.resultHint_label.setMinimumSize(QtCore.QSize(500, 30))
        self.resultHint_label.setMaximumSize(QtCore.QSize(600, 60))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.resultHint_label.setFont(font)
        self.resultHint_label.setObjectName("resultHint_label")
        self.dataTable_Vlayout.addWidget(self.resultHint_label)
        self.data_tableWidget = TableWidget(Students_info_Sno)
        self.data_tableWidget.setMinimumSize(QtCore.QSize(500, 450))
        self.data_tableWidget.setMaximumSize(QtCore.QSize(6000, 1500))
        self.data_tableWidget.setObjectName("data_tableWidget")
        self.data_tableWidget.setColumnCount(0)
        self.data_tableWidget.setRowCount(0)
        self.dataTable_Vlayout.addWidget(self.data_tableWidget)
        self.gridLayout.addLayout(self.dataTable_Vlayout, 5, 0, 1, 7)
        self.select_pushButton = PrimaryPushButton(Students_info_Sno)
        self.select_pushButton.setMinimumSize(QtCore.QSize(120, 40))
        self.select_pushButton.setMaximumSize(QtCore.QSize(150, 40))
        self.select_pushButton.setMouseTracking(True)
        self.select_pushButton.setObjectName("select_pushButton")
        self.gridLayout.addWidget(self.select_pushButton, 2, 5, 1, 1)
        self.hint_label = QtWidgets.QLabel(Students_info_Sno)
        self.hint_label.setMinimumSize(QtCore.QSize(290, 30))
        self.hint_label.setMaximumSize(QtCore.QSize(310, 35))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(18)
        self.hint_label.setFont(font)
        self.hint_label.setObjectName("hint_label")
        self.gridLayout.addWidget(self.hint_label, 1, 3, 1, 1)
        self.Sno_label = QtWidgets.QLabel(Students_info_Sno)
        self.Sno_label.setMinimumSize(QtCore.QSize(60, 0))
        self.Sno_label.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.Sno_label.setFont(font)
        self.Sno_label.setObjectName("Sno_label")
        self.gridLayout.addWidget(self.Sno_label, 2, 0, 1, 1)
        self.Sno_lineEdit = LineEdit(Students_info_Sno)
        self.Sno_lineEdit.setMinimumSize(QtCore.QSize(140, 35))
        self.Sno_lineEdit.setMaximumSize(QtCore.QSize(140, 35))
        self.Sno_lineEdit.setObjectName("Sno_lineEdit")
        self.gridLayout.addWidget(self.Sno_lineEdit, 2, 1, 1, 1)

        self.retranslateUi(Students_info_Sno)
        QtCore.QMetaObject.connectSlotsByName(Students_info_Sno)

    def retranslateUi(self, Students_info_Sno):
        _translate = QtCore.QCoreApplication.translate
        Students_info_Sno.setWindowTitle(_translate("Students_info_Sno", "Form"))
        self.resultHint_label.setText(_translate("Students_info_Sno", "结果将呈现在下方..."))
        self.select_pushButton.setText(_translate("Students_info_Sno", "查询"))
        self.hint_label.setText(_translate("Students_info_Sno", "按学号查询学生信息"))
        self.Sno_label.setText(_translate("Students_info_Sno", "学号:"))
from qfluentwidgets import LineEdit, PrimaryPushButton, TableWidget
