# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\DB_project\ui\setting_return_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import  QWidget

class Ui_setting_return_login(QWidget):
    def setupUi(self, setting_return_login):
        setting_return_login.setObjectName("setting_return_login")
        setting_return_login.resize(948, 798)
        setting_return_login.setMinimumSize(QtCore.QSize(100, 30))
        self.return_pushButton = PrimaryPushButton(setting_return_login)
        self.return_pushButton.setGeometry(QtCore.QRect(360, 320, 180, 50))
        self.return_pushButton.setMinimumSize(QtCore.QSize(120, 40))
        self.return_pushButton.setMaximumSize(QtCore.QSize(180, 50))
        self.return_pushButton.setMouseTracking(True)
        self.return_pushButton.setObjectName("return_pushButton")
        self.title_label = QtWidgets.QLabel(setting_return_login)
        self.title_label.setGeometry(QtCore.QRect(190, 200, 520, 35))
        self.title_label.setMinimumSize(QtCore.QSize(320, 30))
        self.title_label.setMaximumSize(QtCore.QSize(520, 35))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(24)
        self.title_label.setFont(font)
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")

        self.retranslateUi(setting_return_login)
        QtCore.QMetaObject.connectSlotsByName(setting_return_login)

    def retranslateUi(self, setting_return_login):
        _translate = QtCore.QCoreApplication.translate
        setting_return_login.setWindowTitle(_translate("setting_return_login", "Form"))
        self.return_pushButton.setText(_translate("setting_return_login", "返回登录界面"))
from qfluentwidgets import PrimaryPushButton
